name: "Deploy Admin Panel to stage"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      # - name: Install AWS CLI v2
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws --version
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_WORKFLOW_ROLE }}
          role-duration-seconds: 1200

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        env:
          NX_CLOUD_ENABLED: 'false'
          VITE_ENVIRONMENT: STAGE
          VITE_AUTH0_ISSUER: ${{ secrets.VITE_AUTH0_ISSUER }}
          VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_RPC_URL: ${{ secrets.VITE_BASE_SEPOLIA_RPC_URL }}
          VITE_SUBGRAPH_URL: ${{ secrets.VITE_BASE_SEPOLIA_SUBGRAPH_URL }}
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL_STAGE }}
        run: npx nx run admin:build

      - name: Deploy to S3
        run: |
          aws s3 sync apps/admin/dist s3://${{ secrets.STAGE_ADMIN_S3_BUCKET }} --delete
      
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.STAGE_DISTRIBUTION_ID }} \
            --paths "/*"